ajout dockerfile pour python2
coopengo/coog-drone pull request #10
Opened 2019-05-10 09:36 UTC by gautierrognon

nouveau dossier avec son dockerfile pour compatibilité avec python2

2019-05-10 09:56 UTC, jmousset requested changes

2019-05-10 09:56 UTC, jmousset commented on dockerpy2/Dockerfile
> +        werkzeug \
alors en fait, il faudrait utililer les versions de ces libs tels qu'elles sont définis dans le docker file dans coog-admin sur la branche 2.0 . Idéalement, faudrait trouver un moyen de pas avoir à dupliquer l'information (qu'on ait qu'un seul fichier qui fasse référence ). Si jamais t'as une idée ... Et sinon, à minima, mettre les mêmes version que là : https://github.com/coopengo/coog-admin/blob/coog-2.0/images/coog/Dockerfile

2019-05-13 12:55 UTC, gautierrognon commented on dockerpy2/Dockerfile
> +        werkzeug \
done

2019-05-14 07:43 UTC, jmousset requested changes

2019-05-14 07:43 UTC, jmousset commented on dockerpy2/Dockerfile
> +
ligne vide

2019-05-14 09:22 UTC, gautierrognon commented on dockerpy2/Dockerfile
> +
done !!

2019-05-14 09:31 UTC, jmousset approved these changes

2019-05-14 09:31 UTC, merged