Allow multiple changelog lines
coopengo/coog-drone pull request #4
Opened 2018-01-31 11:22 UTC by JCavallo

2018-02-01 13:23 UTC, alikefia requested changes

2018-02-01 13:23 UTC, alikefia commented on checks/check-meta.py
> -                if len(lines) == 1:
On accepte un commit qui fixe plusieurs issues?
Dans ce cas on doit cross-check / body?

2018-02-01 13:40 UTC, JCavallo commented on checks/check-meta.py
> -                if len(lines) == 1:
En théorie oui. Mais surtout (et c'est le but ici), il n'est pas rare que l'on corrige une typo sur une ligne précédente

2018-02-05 10:01 UTC, JCavallo commented
Up @alikefia

2018-02-08 14:02 UTC, merged